---
title: "Welcome to the jungle"
description: | 
  I have reluctantly decided to create a new blog. Some thoughts on 
  what I hope to achieve, having tried my hand at blogging so very many times 
  before
author:
  - first_name: "Danielle"
    last_name: "Navarro"
    url: https://djnavarro.net
    affiliation: UNSW Sydney
    affiliation_url: https://unsw.edu.au
    orcid_id: 0000-0001-7648-6578
date: 2021-04-05
output:
  distill::distill_article:
    self_contained: false
---


<!--------------- my typical setup ----------------->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r meta, echo=FALSE}
# import utility functions as a module
box::use(../../source/utils[
  set_meta_tags, set_redirect
])

# specify meta tags for twitter card (can differ from post summary)
set_meta_tags(
  title =  "Welcome to the jungle", 
  description = "Some thoughts on starting over, when I have tried my hand at blogging so very many times before"
)

# create a redirect for this post
set_redirect("welcome")
```

<!--------------- post begins here ----------------->

Hello


