---
title: "A new post"
description: | 
  Description of the post
params:
  slug: template
author:
  - first_name: "Danielle"
    last_name: "Navarro"
    url: https://djnavarro.net
    affiliation: UNSW Sydney
    affiliation_url: https://unsw.edu.au
    orcid_id: 0000-0001-7648-6578
date: 1900-01-01
draft: true
creative_commons: CC BY
citation_url: https://blog.djnavarro.net/template
repository_url: https://github.com/djnavarro/distill-blog
output:
  distill::distill_article:
    self_contained: false
---


<!--------------- my typical setup ----------------->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r box, echo=FALSE}
# ensure box knows where this post is located
blogroot <- rprojroot::find_root(".blogroot")
postroot <- fs::path(blogroot, "_posts", params$slug)
postfile <- fs::path(postroot, paste0(params$slug, ".Rmd"))

box::set_script_path(postfile)

# import utility functions from local copy of utils.R
old_opts <- options(box.path = postroot)
box::use(./helpers[
  set_meta, 
  set_redirect, 
  set_source, 
  set_session,
  set_lockfile,
  set_timestamp
])
options(old_opts)
```


```{r meta, echo=FALSE}
# specify meta tags for twitter card (can differ from post summary)
set_meta(
  title =  "A new post", 
  description = "Description of the post"
)
```



<!--------------- post begins here ----------------->

This is a template post




<!--------------- appendices go here ----------------->

## Last updated {.appendix}

`r set_timestamp("Australia/Sydney")`

## Details {.appendix}

[source code](`r set_source(params$slug)`), [session info](`r set_session(params$slug)`), [lockfile](`r set_lockfile(params$slug)`)



<!--------------- miscellanea ----------------->

```{r redirect, echo=FALSE}
# set_redirect(params$slug) 
```




