---
title: "Setting up a git credential helper"
description: |
  A short description of the post
params:
  slug: git-credential-helpers
author:
  - first_name: "Danielle"
    last_name: "Navarro"
    url: https://djnavarro.net
    affiliation: UNSW Sydney
    affiliation_url: https://unsw.edu.au
    orcid_id: 0000-0001-7648-6578
date: 2021-07-08
creative_commons: CC BY
citation_url: https://blog.djnavarro.net/git-credential-helpers
repository_url: https://github.com/djnavarro/distill-blog
output:
  distill::distill_article:
    self_contained: false
---


<!--------------- my typical setup ----------------->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r box, echo=FALSE}
# ensure box knows where this post is located
box::set_script_path(
  path = here::here("_posts", params$slug, paste0(params$slug, ".Rmd"))
)

# import utility functions as a module
box::use(../../source/utils[
  set_meta, 
  set_redirect, 
  set_source, 
  set_session,
  set_lockfile,
  set_timestamp
])
```

```{r meta, echo=FALSE}
set_meta(
  title =  "Setting up a git credential helper", 
  description = "..."
)
```

```{r include=FALSE}
aside <- function(text) {
  return(htmltools::tag("aside", list(text)))
}
image <- function(src, width = "100%") {
    htmltools::img(src = src, width = width)
}
```


<!--------------- post begins here ----------------->

The [Happy Git and GitHub for the useR](https://happygitwithr.com/credential-caching.html) chapter on credential caching

Enable 2FA: https://github.com/settings/security


What you need to do

```{bash, eval=FALSE}
# install libsecret if you don't already have it
sudo apt install libsecret-1-0 libsecret-1-dev

# ensure that the there's a libsecret directory to store creds
sudo make --directory=/usr/share/doc/git/contrib/credential/libsecret

# register the credentials
git config --global credential.helper \
  /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
```


Check at the command line

```{bash, eval=FALSE}
git config --global credential.helper  
```

Check from within R

```{r}
gitcreds::gitcreds_list_helpers()
```

Now we can follow the process...

```{r, eval=FALSE}
usethis::create_github_token()
gitcreds::gitcreds_set()
```

Usethis is now happy, and `pr_*()` functions now work as expected...

```{r, eval=FALSE}
usethis::git_sitrep()
```

```{r}
gitcreds::gitcreds_get()
```

<!--------------- appendices go here ----------------->

## Last updated {.appendix}

`r set_timestamp("Australia/Sydney")`

## Details {.appendix}

[source code](`r set_source(params$slug)`), [session info](`r set_session(params$slug)`), [lockfile](`r set_lockfile(params$slug)`)


<!--------------- miscellanea ----------------->

```{r redirect, echo=FALSE}
set_redirect(params$slug)
```


